"""
Content Renderer
Ahmed Adawy Tech Capsules
"""

from html import escape
from html.parser import HTMLParser

from highlighter import SyntaxHighlighter
from parser import (
    BulletList,
    CodeBlock,
    Heading,
    Image,
    Paragraph,
    Table,
)


class _InlineHTMLSanitizer(HTMLParser):
    """
    Safely render the limited inline HTML generated by parser.py.

    The Markdown parser intentionally converts inline formatting into
    HTML tags such as <strong>, <em>, <code>, and <a>.

    This sanitizer allows only those tags and safely escapes everything
    else instead of escaping the generated HTML itself.
    """

    ALLOWED_TAGS = {
        "strong",
        "em",
        "code",
        "a",
    }

    def __init__(self):
        super().__init__(
            convert_charrefs=False
        )
        self.parts = []

    def handle_starttag(self, tag, attrs):

        tag = tag.lower()

        if tag not in self.ALLOWED_TAGS:
            return

        if tag == "a":

            href = ""

            for name, value in attrs:

                if name.lower() == "href":
                    href = value or ""
                    break

            self.parts.append(
                f'<a href="{escape(href, quote=True)}">'
            )

            return

        self.parts.append(
            f"<{tag}>"
        )

    def handle_startendtag(self, tag, attrs):

        # Inline self-closing tags are not generated by our parser.
        # Ignore them deliberately.
        return

    def handle_endtag(self, tag):

        tag = tag.lower()

        if tag in self.ALLOWED_TAGS:
            self.parts.append(
                f"</{tag}>"
            )

    def handle_data(self, data):

        self.parts.append(
            escape(data)
        )

    def handle_entityref(self, name):

        self.parts.append(
            f"&{name};"
        )

    def handle_charref(self, name):

        self.parts.append(
            f"&#{name};"
        )

    def handle_comment(self, data):

        # Comments are never part of the rendered inline content.
        return

    def result(self):

        return "".join(self.parts)


def _render_inline_html(value):
    """
    Render HTML generated by parser.py while keeping the output safe.
    """

    if value is None:
        return ""

    value = str(value)

    sanitizer = _InlineHTMLSanitizer()

    sanitizer.feed(value)
    sanitizer.close()

    return sanitizer.result()


def _plain_text(value):
    """
    Convert parser-generated inline HTML into readable plain text.

    Used for attributes such as heading IDs where HTML markup should
    never become part of the identifier.
    """

    if value is None:
        return ""

    parser = _InlineHTMLSanitizer()

    parser.feed(str(value))
    parser.close()

    return "".join(
        part.replace("<strong>", "")
            .replace("</strong>", "")
            .replace("<em>", "")
            .replace("</em>", "")
            .replace("<code>", "")
            .replace("</code>", "")
            .replace("<a>", "")
            .replace("</a>", "")
        for part in parser.parts
    )


class ContentRenderer:

    def __init__(self):

        self.highlighter = SyntaxHighlighter()

    def render(self, document):

        html = []

        for node in document:

            if isinstance(node, Heading):

                plain_heading = _plain_text(
                    node.text
                )

                heading_id = (
                    plain_heading
                    .lower()
                    .replace(" ", "-")
                    .replace(".", "")
                    .replace(",", "")
                    .replace(":", "")
                    .replace("/", "-")
                )

                html.append(
                    f'<h{node.level} id="{escape(heading_id, quote=True)}">'
                    f"{_render_inline_html(node.text)}"
                    f"</h{node.level}>"
                )

            elif isinstance(node, Paragraph):

                html.append(
                    f"<p>{_render_inline_html(node.text)}</p>"
                )

            elif isinstance(node, BulletList):

                html.append("<ul>")

                for item in node.items:

                    html.append(
                        f"<li>{_render_inline_html(item)}</li>"
                    )

                html.append("</ul>")

            elif isinstance(node, CodeBlock):

                html.append(
                    self.highlighter.highlight(
                        node.text,
                        node.language,
                    )
                )

            elif isinstance(node, Image):

                html.append(
                    f'<img src="{escape(node.src, quote=True)}" '
                    f'alt="{escape(node.alt, quote=True)}">'
                )

            elif isinstance(node, Table):

                table = ["<table>"]

                if node.header:

                    table.extend(
                        [
                            "<thead>",
                            "<tr>",
                        ]
                    )

                    for header in node.header:

                        table.append(
                            f"<th>"
                            f"{_render_inline_html(header)}"
                            f"</th>"
                        )

                    table.extend(
                        [
                            "</tr>",
                            "</thead>",
                        ]
                    )

                table.append("<tbody>")

                for row in node.rows:

                    table.append("<tr>")

                    for cell in row:

                        table.append(
                            f"<td>"
                            f"{_render_inline_html(cell)}"
                            f"</td>"
                        )

                    table.append("</tr>")

                table.extend(
                    [
                        "</tbody>",
                        "</table>",
                    ]
                )

                html.append(
                    "\n".join(table)
                )

            else:

                print(
                    "Warning: Unsupported node "
                    f"{type(node).__name__}"
                )

        return "\n".join(html)
